// <auto-generated />
using System;
using IPS.AutoPost.Core.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPS.AutoPost.Core.Migrations
{
    [DbContext(typeof(AutoPostDatabaseContext))]
    [Migration("20260430143705_InitialGenericTables")]
    partial class InitialGenericTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericAuthConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("api_key");

                    b.Property<string>("AuthKey")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("auth_key");

                    b.Property<string>("AuthPurpose")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("auth_purpose");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("auth_type");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("extra_json");

                    b.Property<int>("JobConfigId")
                        .HasColumnType("int")
                        .HasColumnName("job_config_id");

                    b.Property<string>("Password")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("password");

                    b.Property<string>("SecretArn")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("secret_arn");

                    b.Property<string>("TokenUrl")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("token_url");

                    b.Property<string>("Username")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("JobConfigId", "AuthPurpose")
                        .HasDatabaseName("IX_auth_config_job_purpose");

                    b.ToTable("generic_auth_configuration", (string)null);
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericEmailConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailBcc")
                        .HasColumnType("NVARCHAR(1000)")
                        .HasColumnName("email_bcc");

                    b.Property<string>("EmailCc")
                        .HasColumnType("NVARCHAR(1000)")
                        .HasColumnName("email_cc");

                    b.Property<string>("EmailSubject")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("email_subject");

                    b.Property<string>("EmailTemplate")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("email_template");

                    b.Property<string>("EmailTo")
                        .HasColumnType("NVARCHAR(1000)")
                        .HasColumnName("email_to");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("email_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("JobConfigId")
                        .HasColumnType("int")
                        .HasColumnName("job_config_id");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("smtp_password");

                    b.Property<int?>("SmtpPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(587)
                        .HasColumnName("smtp_port");

                    b.Property<string>("SmtpServer")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("smtp_server");

                    b.Property<bool>("SmtpUseSsl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("smtp_use_ssl");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("smtp_username");

                    b.HasKey("Id");

                    b.HasIndex("JobConfigId", "EmailType")
                        .HasDatabaseName("IX_email_config_job_type");

                    b.ToTable("generic_email_configuration", (string)null);
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericExecutionHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("client_type");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("error_details");

                    b.Property<string>("ExecutionType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("execution_type");

                    b.Property<int>("JobConfigId")
                        .HasColumnType("int")
                        .HasColumnName("job_config_id");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<int>("RecordsFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("records_failed");

                    b.Property<int>("RecordsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("records_processed");

                    b.Property<int>("RecordsSucceeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("records_succeeded");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("status");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("trigger_type");

                    b.Property<int?>("TriggeredByUser")
                        .HasColumnType("int")
                        .HasColumnName("triggered_by_user");

                    b.HasKey("Id");

                    b.HasIndex("JobConfigId", "StartTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_exec_history_job");

                    b.HasIndex("Status", "StartTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_exec_history_status");

                    b.ToTable("generic_execution_history", (string)null);
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericExecutionScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CronExpression")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("cron_expression");

                    b.Property<string>("ExecutionTime")
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("execution_time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("JobConfigId")
                        .HasColumnType("int")
                        .HasColumnName("job_config_id");

                    b.Property<DateTime?>("LastExecutionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_execution_time");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(20)")
                        .HasDefaultValue("POST")
                        .HasColumnName("schedule_type");

                    b.HasKey("Id");

                    b.HasIndex("JobConfigId", "ScheduleType")
                        .HasDatabaseName("IX_exec_schedule_job_type");

                    b.ToTable("generic_execution_schedule", null, t =>
                        {
                            t.HasCheckConstraint("CHK_schedule_has_time", "execution_time IS NOT NULL OR cron_expression IS NOT NULL");
                        });
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericFeedConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Delimiter")
                        .HasColumnType("VARCHAR(5)")
                        .HasColumnName("delimiter");

                    b.Property<string>("FeedConfigJson")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("feed_config_json");

                    b.Property<string>("FeedName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("feed_name");

                    b.Property<string>("FeedSourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(20)")
                        .HasDefaultValue("REST")
                        .HasColumnName("feed_source_type");

                    b.Property<string>("FeedTableName")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("feed_table_name");

                    b.Property<string>("FeedUrl")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("feed_url");

                    b.Property<string>("FileFormat")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("file_format");

                    b.Property<string>("FtpFilePattern")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ftp_file_pattern");

                    b.Property<string>("FtpHost")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ftp_host");

                    b.Property<string>("FtpPath")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("ftp_path");

                    b.Property<int?>("FtpPort")
                        .HasColumnType("int")
                        .HasColumnName("ftp_port");

                    b.Property<bool>("HasHeader")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("has_header");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("JobConfigId")
                        .HasColumnType("int")
                        .HasColumnName("job_config_id");

                    b.Property<string>("KeyColumn")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("key_column");

                    b.Property<DateTime?>("LastDownloadTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_download_time");

                    b.Property<string>("LocalFilePath")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("local_file_path");

                    b.Property<string>("RefreshStrategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(20)")
                        .HasDefaultValue("TRUNCATE")
                        .HasColumnName("refresh_strategy");

                    b.Property<string>("S3Bucket")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("s3_bucket");

                    b.Property<string>("S3KeyPrefix")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("s3_key_prefix");

                    b.HasKey("Id");

                    b.HasIndex("JobConfigId")
                        .HasDatabaseName("IX_feed_config_job_id");

                    b.ToTable("generic_feed_configuration", (string)null);
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericFeedDownloadHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DownloadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("download_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("error_message");

                    b.Property<string>("FeedName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("feed_name");

                    b.Property<bool>("IsManual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_manual");

                    b.Property<int>("JobConfigId")
                        .HasColumnType("int")
                        .HasColumnName("job_config_id");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("int")
                        .HasColumnName("record_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobConfigId", "DownloadDate")
                        .HasDatabaseName("IX_feed_download_history_job_date");

                    b.ToTable("generic_feed_download_history", (string)null);
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericFieldMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(50)")
                        .HasDefaultValue("VARCHAR")
                        .HasColumnName("data_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.Property<int>("JobConfigId")
                        .HasColumnType("int")
                        .HasColumnName("job_config_id");

                    b.Property<string>("MappingType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("mapping_type");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("SourceField")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("source_field");

                    b.Property<string>("TargetField")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("target_field");

                    b.Property<string>("TransformRule")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("transform_rule");

                    b.HasKey("Id");

                    b.HasIndex("JobConfigId", "MappingType", "SortOrder")
                        .HasDatabaseName("IX_field_mapping_job_type_sort");

                    b.ToTable("generic_field_mapping", (string)null);
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericJobConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowAutoPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_auto_post");

                    b.Property<string>("AuthPassword")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("auth_password");

                    b.Property<string>("AuthType")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("auth_type");

                    b.Property<string>("AuthUsername")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("auth_username");

                    b.Property<string>("ClientConfigJson")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("client_config_json");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("client_type");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DbConnectionString")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("db_connection_string");

                    b.Property<int>("DefaultUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100)
                        .HasColumnName("default_user_id");

                    b.Property<string>("DetailTable")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("detail_table");

                    b.Property<string>("DetailUidColumn")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("detail_uid_column");

                    b.Property<bool>("DownloadFeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("download_feed");

                    b.Property<string>("FeedDownloadPath")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("feed_download_path");

                    b.Property<string>("HeaderTable")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("header_table");

                    b.Property<string>("HistoryTable")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("history_table");

                    b.Property<string>("ImageParentPath")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("image_parent_path");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLegacyJob")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_legacy_job");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("job_name");

                    b.Property<DateTime?>("LastDownloadTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_download_time");

                    b.Property<DateTime?>("LastPostTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_post_time");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_date");

                    b.Property<string>("NewUiImageParentPath")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("new_ui_image_parent_path");

                    b.Property<string>("OutputFilePath")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("output_file_path");

                    b.Property<string>("PostServiceUrl")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("post_service_url");

                    b.Property<int?>("PrimaryFailQueueId")
                        .HasColumnType("int")
                        .HasColumnName("primary_fail_queue_id");

                    b.Property<int?>("QuestionQueueId")
                        .HasColumnType("int")
                        .HasColumnName("question_queue_id");

                    b.Property<int?>("SecondaryFailQueueId")
                        .HasColumnType("int")
                        .HasColumnName("secondary_fail_queue_id");

                    b.Property<string>("SourceQueueId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("source_queue_id");

                    b.Property<int?>("SuccessQueueId")
                        .HasColumnType("int")
                        .HasColumnName("success_queue_id");

                    b.Property<int?>("TerminatedQueueId")
                        .HasColumnType("int")
                        .HasColumnName("terminated_queue_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientType")
                        .HasDatabaseName("IX_generic_job_config_client_type");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_generic_job_config_is_active");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("IX_generic_job_config_job_id");

                    b.ToTable("generic_job_configuration", (string)null);
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericPostHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("client_type");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.Property<bool>("ManuallyPosted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("manually_posted");

                    b.Property<string>("OutputFilePath")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("output_file_path");

                    b.Property<DateTime>("PostDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("post_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PostRequest")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("post_request");

                    b.Property<string>("PostResponse")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("post_response");

                    b.Property<int>("PostedBy")
                        .HasColumnType("int")
                        .HasColumnName("posted_by");

                    b.Property<string>("StepName")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("step_name");

                    b.HasKey("Id");

                    b.HasIndex("ClientType")
                        .HasDatabaseName("IX_generic_post_history_client");

                    b.HasIndex("ItemId", "JobId")
                        .HasDatabaseName("IX_generic_post_history_item");

                    b.ToTable("generic_post_history", (string)null);
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericQueueRoutingRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("JobConfigId")
                        .HasColumnType("int")
                        .HasColumnName("job_config_id");

                    b.Property<int>("QueueId")
                        .HasColumnType("int")
                        .HasColumnName("queue_id");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("result_type");

                    b.HasKey("Id");

                    b.HasIndex("JobConfigId", "ResultType")
                        .HasDatabaseName("IX_queue_routing_job_result");

                    b.ToTable("generic_queue_routing_rules", (string)null);
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericAuthConfigurationEntity", b =>
                {
                    b.HasOne("IPS.AutoPost.Core.Migrations.Entities.GenericJobConfigurationEntity", "JobConfiguration")
                        .WithMany("AuthConfigurations")
                        .HasForeignKey("JobConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobConfiguration");
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericEmailConfigurationEntity", b =>
                {
                    b.HasOne("IPS.AutoPost.Core.Migrations.Entities.GenericJobConfigurationEntity", "JobConfiguration")
                        .WithMany("EmailConfigurations")
                        .HasForeignKey("JobConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobConfiguration");
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericExecutionHistoryEntity", b =>
                {
                    b.HasOne("IPS.AutoPost.Core.Migrations.Entities.GenericJobConfigurationEntity", "JobConfiguration")
                        .WithMany("ExecutionHistories")
                        .HasForeignKey("JobConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobConfiguration");
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericExecutionScheduleEntity", b =>
                {
                    b.HasOne("IPS.AutoPost.Core.Migrations.Entities.GenericJobConfigurationEntity", "JobConfiguration")
                        .WithMany("ExecutionSchedules")
                        .HasForeignKey("JobConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobConfiguration");
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericFeedConfigurationEntity", b =>
                {
                    b.HasOne("IPS.AutoPost.Core.Migrations.Entities.GenericJobConfigurationEntity", "JobConfiguration")
                        .WithMany("FeedConfigurations")
                        .HasForeignKey("JobConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobConfiguration");
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericFieldMappingEntity", b =>
                {
                    b.HasOne("IPS.AutoPost.Core.Migrations.Entities.GenericJobConfigurationEntity", "JobConfiguration")
                        .WithMany("FieldMappings")
                        .HasForeignKey("JobConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobConfiguration");
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericQueueRoutingRuleEntity", b =>
                {
                    b.HasOne("IPS.AutoPost.Core.Migrations.Entities.GenericJobConfigurationEntity", "JobConfiguration")
                        .WithMany("QueueRoutingRules")
                        .HasForeignKey("JobConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobConfiguration");
                });

            modelBuilder.Entity("IPS.AutoPost.Core.Migrations.Entities.GenericJobConfigurationEntity", b =>
                {
                    b.Navigation("AuthConfigurations");

                    b.Navigation("EmailConfigurations");

                    b.Navigation("ExecutionHistories");

                    b.Navigation("ExecutionSchedules");

                    b.Navigation("FeedConfigurations");

                    b.Navigation("FieldMappings");

                    b.Navigation("QueueRoutingRules");
                });
#pragma warning restore 612, 618
        }
    }
}
