namespace IPS.AutoPost.Plugins.Sevita.Models;

/// <summary>
/// Post failure notification email configuration for the Sevita plugin.
/// Loaded from the <c>get_sevita_configurations</c> stored procedure result.
/// </summary>
/// <remarks>
/// Used by <c>SevitaPostStrategy.SendNotificationEmailAsync()</c> to send a batch
/// failure notification email after all workitems are processed.
/// The email is sent only when at least one workitem failed and
/// <see cref="EmailTo"/> is non-empty.
/// </remarks>
public class FailedPostConfiguration
{
    /// <summary>
    /// Semicolon-delimited list of recipient email addresses for post failure notifications.
    /// Split by <c>';'</c> before sending.
    /// </summary>
    public string EmailTo { get; set; } = string.Empty;

    /// <summary>
    /// HTML email template for the post failure notification.
    /// Contains the <c>[[AppendTable]]</c> placeholder which is replaced with the
    /// HTML table of failed records generated by <c>GenerateHtmlTable()</c>.
    /// </summary>
    public string EmailTemplate { get; set; } = string.Empty;

    /// <summary>
    /// Subject line for the post failure notification email.
    /// </summary>
    public string EmailSubject { get; set; } = string.Empty;
}
