namespace IPS.AutoPost.Core.Models;

/// <summary>
/// Represents a row in the <c>generic_execution_history</c> table.
/// Written by <c>AutoPostOrchestrator</c> after each execution run (post or feed),
/// capturing aggregate statistics for monitoring and the Status API endpoint.
/// </summary>
public class GenericExecutionHistory
{
    /// <summary>Primary key (auto-generated by the database).</summary>
    public long Id { get; set; }

    /// <summary>Foreign key to <c>generic_job_configuration.id</c>.</summary>
    public int JobConfigId { get; set; }

    /// <summary>Client type string (e.g. "INVITEDCLUB", "SEVITA").</summary>
    public string ClientType { get; set; } = string.Empty;

    /// <summary>Numeric job identifier.</summary>
    public int JobId { get; set; }

    /// <summary>
    /// Type of execution: "POST" or "FEED".
    /// Determines which pipeline produced this record.
    /// </summary>
    public string ExecutionType { get; set; } = string.Empty;

    /// <summary>
    /// How this execution was triggered: "Scheduled" or "Manual".
    /// </summary>
    public string TriggerType { get; set; } = string.Empty;

    /// <summary>
    /// Execution outcome: "SUCCESS", "PARTIAL_SUCCESS", or "FAILED".
    /// "PARTIAL_SUCCESS" means at least one workitem succeeded and at least one failed.
    /// </summary>
    public string Status { get; set; } = string.Empty;

    /// <summary>Total number of workitems attempted in this run.</summary>
    public int RecordsProcessed { get; set; }

    /// <summary>Number of workitems routed to the success queue.</summary>
    public int RecordsSucceeded { get; set; }

    /// <summary>Number of workitems routed to a failure queue.</summary>
    public int RecordsFailed { get; set; }

    /// <summary>UTC timestamp when this execution run started.</summary>
    public DateTime StartTime { get; set; }

    /// <summary>UTC timestamp when this execution run completed.</summary>
    public DateTime EndTime { get; set; }

    /// <summary>
    /// Total duration of the execution run in seconds.
    /// Computed as <c>(EndTime - StartTime).TotalSeconds</c>.
    /// </summary>
    public double DurationSeconds => (EndTime - StartTime).TotalSeconds;

    /// <summary>
    /// Full exception details when <see cref="Status"/> is "FAILED".
    /// Null on success or partial success.
    /// </summary>
    public string? ErrorDetails { get; set; }
}
