namespace IPS.AutoPost.Core.Models;

/// <summary>
/// Represents a row in the <c>generic_post_history</c> table.
/// Written by the Core_Engine after every workitem is processed, capturing
/// the full request/response payload for audit and debugging purposes.
/// Client-specific history tables (e.g. <c>post_to_invitedclub_history</c>) are
/// written by the plugin in addition to this generic record.
/// </summary>
public class GenericPostHistory
{
    /// <summary>Primary key (auto-generated by the database).</summary>
    public long Id { get; set; }

    /// <summary>Foreign key to <c>generic_job_configuration.id</c>.</summary>
    public int JobConfigId { get; set; }

    /// <summary>Client type string (e.g. "INVITEDCLUB", "SEVITA").</summary>
    public string ClientType { get; set; } = string.Empty;

    /// <summary>Numeric job identifier.</summary>
    public int JobId { get; set; }

    /// <summary>The <c>ItemId</c> of the workitem that was processed.</summary>
    public long ItemId { get; set; }

    /// <summary>
    /// Name of the processing step (e.g. "PostInvoice", "PostAttachment", "CalculateTax").
    /// Allows multi-step plugins to record each API call separately.
    /// </summary>
    public string StepName { get; set; } = string.Empty;

    /// <summary>
    /// Serialized JSON of the request payload sent to the external ERP API.
    /// May be null for steps that do not send a request body.
    /// </summary>
    public string? PostRequest { get; set; }

    /// <summary>
    /// Serialized JSON of the response received from the external ERP API.
    /// May be null when no response was received (e.g. network error).
    /// </summary>
    public string? PostResponse { get; set; }

    /// <summary>UTC timestamp when this history record was written.</summary>
    public DateTime PostDate { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// User ID of the person who triggered the post.
    /// Matches <c>GenericJobConfig.DefaultUserId</c> for scheduled posts,
    /// or the authenticated user's ID for manual posts.
    /// </summary>
    public int PostedBy { get; set; }

    /// <summary>
    /// <c>true</c> when this workitem was posted via a manual trigger from the Workflow UI.
    /// <c>false</c> for scheduled posts.
    /// </summary>
    public bool ManuallyPosted { get; set; }
}
